all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-34-216-129-139.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-52-25-184-53.us-west-2.compute.amazonaws.com
